    name: Example key vault flow

    on: [push]

    jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - uses: actions/checkout@v2
        - uses: Azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - uses: Azure/get-keyvault-secrets@v1
        with: 
            keyvault: "webappdevops"
            secrets: 'wHi9YX8peY7D5jnM2gau2tqx8w2FNAV8NZT1BG9/Zx+ACRCuO6Dw, webappregi1'
        id: myGetSecretAction
        - uses: azure/docker-login@v1
        with:
            login-server: ${{ steps.myGetSecretAction.outputs.containerUsername }}.azurecr.io
            username: ${{ steps.myGetSecretAction.outputs.containerUsername }}
            password: ${{ steps.myGetSecretAction.outputs.containerPassword }}
